# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

restaurant_1 = Restaurant.create(name: 'Mui Cha 小野喫茶店', image: 'image1.png', description: 'Chinese', delivery_fee: 200)
restaurant_2 = Restaurant.create(name: 'ドミノ・ピザ鶴見寺谷店', image: 'image2.png', description: 'Pizza', delivery_fee: 100)
restaurant_3 = Restaurant.create(name: '台湾悪魔ジーパイ　川崎', image: 'image3.png', description: 'Asian', delivery_fee: 450)
restaurant_4 = Restaurant.create(name: 'からあげ金星　反町店', image: 'image4.png', description: 'Japanese', delivery_fee: 150)
restaurant_5 = Restaurant.create(name: 'フォルクス　鶴見寺尾店', image: 'image5.png', description: 'Western', delivery_fee: 100)
restaurant_6 = Restaurant.create(name: '溶岩焼きビビンパ専門店', image: 'image6.png', description: 'Korea', delivery_fee: 350)
restaurant_7 = Restaurant.create(name: '鳥煎道タピオカ 川崎店', image: 'image7.png', description: 'Beverages', delivery_fee: 200)
restaurant_8 = Restaurant.create(name: 'ターリー屋　川崎西口通り店', image: 'image8.png', description: 'Indian', delivery_fee: 400)
restaurant_9 = Restaurant.create(name: 'タイ食堂　テンヌン', image: 'image9.png', description: 'Thai', delivery_fee: 150)
restaurant_10 = Restaurant.create(name: 'サンジェルマン菊名店', image: 'image10.png', description: 'Cake', delivery_fee: 350)

Menu.create(restaurant_id: restaurant_1.id, name: '老北京鶏肉巻', image: 'muicha1.png', description: '北京ダックとちょっと似ている風味です。揚げたての鶏もも肉とパリパリレタスを巻き込み、本格的な外国の味になっております。是非一度お試しください。', price: 590)
Menu.create(restaurant_id: restaurant_1.id, name: '台湾風チキンハンバーガー', image: 'muicha2.png', description: 'ハンバーガーは一番柔らかい鶏もも肉を使っております。すべて揚げたてなんので、その美味しさは一口だけで分かります。日本のから揚げとは食感が全然違いますので、揚げたてのパリパリする食感が最高です。', price: 590)
Menu.create(restaurant_id: restaurant_1.id, name: 'Strawberry Cheese Foam Tea', image: 'muicha3.png', description: '(500ml) 当店全品タピオカ無しの提供です、タピオカご希望のお客様はトッピングしてください。', price: 590)
Menu.create(restaurant_id: restaurant_1.id, name: 'Blueberry Cheese Foam Tea', image: 'muicha4.png', description: '(500ml) 当店全品タピオカ無しの提供です、タピオカご希望のお客様はトッピングしてください。', price: 590)
Menu.create(restaurant_id: restaurant_1.id, name: 'Passion Fruit Tea', image: 'muicha5.png', description: '(500ml) 店全品タピオカ無しの提供です、タピオカご希望のお客様はトッピングしてください。', price: 550)
Menu.create(restaurant_id: restaurant_1.id, name: '楊枝甘露(香港発祥の名物)', image: 'muicha6.png', description: '(500ml) 当店全品タピオカ無しの提供です、タピオカご希望のお客様はトッピングしてください。', price: 650)

Menu.create(restaurant_id: restaurant_2.id, name: 'Margherita Pizza Sandwich', image: 'domino1.png', description: 'Freshly cherry tomato with basil topping.■Tomato Sauce, Italian Bocconcini, Basil, Cherry Tomato', price: 499)
Menu.create(restaurant_id: restaurant_2.id, name: 'Quattro Nippon', image: 'domino2.png', description: '1. Charcoal Grilled Chiki-Teri, 2. Hokkaido 3 Cheese, 3. Spicy Mayo & Mochi, 4. Char-grilled Beef', price: 2600)
Menu.create(restaurant_id: restaurant_2.id, name: 'Charcoal Grilled Chiki-Teri', image: 'domino3.png', description: 'Charcoal flavored Chicken Teriyaki with sizzling mayo.■Tomato Sauce, Teriyaki Chicken, Spinach, Mayonnaise, Corn', price: 2630)
Menu.create(restaurant_id: restaurant_2.id, name: 'Pizza Rice Bowl Domino Deluxe', image: 'domino4.png', description: 'Butter Rice, Tomato Sauce, Onion, Green Peppers, Pepperonit, Italian Sausage, Mushrooms', price: 1099)
Menu.create(restaurant_id: restaurant_2.id, name: 'Fried Chicken', image: 'domino5.png', description: 'Tender and juicy chicken with less fat!', price: 299)
Menu.create(restaurant_id: restaurant_2.id, name: 'Egg Custard Tart', image: 'domino6.png', description: 'Crispy, fragrant pie brimming with custard reminiscent of creme caramel! Try this dessert once, and you be hooked.', price: 299)

Menu.create(restaurant_id: restaurant_3.id, name: '台湾悪魔鶏排', image: 'taiwan1.png', description: '原材料まですべて台湾から輸入するので、台湾のままの味再現します。味は種類があるので楽しんで選んでください。', price: 880)
Menu.create(restaurant_id: restaurant_3.id, name: 'ピーチ ジャスミン グリーンティー エード', image: 'taiwan2.png', description: 'ピーチの甘くジューシーな味わいをすっきりとした後味に仕上げたティー エード。アロエをトッピングして、シャキシャキの食感をアクセントにするのがおすすめ。', price: 550)
Menu.create(restaurant_id: restaurant_3.id, name: '紅茶ミルクティー Black Milk Tea (500ml)', image: 'taiwan3.png', description: '台湾産高級のアールグレイ茶を使用し、こだわりの味にしています。 Special flavor, made with high-quality Taiwanese earl grey tea.', price: 550)
Menu.create(restaurant_id: restaurant_3.id, name: 'ストロベリーラテ', image: 'taiwan4.png', description: '濃厚ないちご味.果肉がたっぷり含まれている、お勧めです。', price: 620)
Menu.create(restaurant_id: restaurant_3.id, name: 'ポテトフライ', image: 'taiwan5.png', description: '', price: 450)
Menu.create(restaurant_id: restaurant_3.id, name: '揚げ手羽先', image: 'taiwan6.png', description: '', price: 230)

Menu.create(restaurant_id: restaurant_4.id, name: 'からあげそぼろ弁当', image: 'japanese1.png', description: '特製醤油で炊き上げた自家製そぼろは旨味抜群！ 金星1番人気お弁当', price: 860)
Menu.create(restaurant_id: restaurant_4.id, name: '金星全部盛り弁当', image: 'japanese2.png', description: 'からあげ5種オールスター！ 金星2番人気お弁当！！(黒1個  白1個  赤1個  黄1個  茶1個  そぼろ)', price: 1090)
Menu.create(restaurant_id: restaurant_4.id, name: 'チキンタルタル弁当', image: 'japanese3.png', description: '秘伝のかえし醤油を使用！', price: 790)
Menu.create(restaurant_id: restaurant_4.id, name: 'からあげ 黒', image: 'japanese4.png', description: '（単品）福島県郡山直送！特製醤油を使った定番！', price: 180)
Menu.create(restaurant_id: restaurant_4.id, name: 'からあげ 赤', image: 'japanese5.png', description: '（単品）辛いぜ！！', price: 180)
Menu.create(restaurant_id: restaurant_4.id, name: 'からあげ 茶', image: 'japanese6.png', description: '（単品）甘旨のこだわり味噌がたまりません！', price: 200)

Menu.create(restaurant_id: restaurant_5.id, name: 'ガーリックバターチキン弁当', image: 'westen1.png', description: 'パリッとグリルしたジューシーチキンをガーリックソースでどうぞ。※ライス付き', price: 1080)
Menu.create(restaurant_id: restaurant_5.id, name: 'ハンバーグ＆チキン弁当', image: 'westen2.png', description: '合い挽きハンバーグ170gとチキンステーキ100gでボリュームたっぷり。※ライス付き', price: 1580)
Menu.create(restaurant_id: restaurant_5.id, name: 'ガーリックバターチキン弁当', image: 'westen3.png', description: 'パリッとグリルしたジューシーチキンをガーリックソースでどうぞ。※ライス付き', price: 1080)
Menu.create(restaurant_id: restaurant_5.id, name: 'ビーフ100％フォルクスハンバーグ', image: 'westen4.png', description: 'フォルクス伝統のビーフ100％ハンバーグ。デミグラスソースでお召し上がりください。', price: 1380)
Menu.create(restaurant_id: restaurant_5.id, name: 'ビーフ100%ハンバーグ＆ソーセージ', image: 'westen5.png', description: 'ビーフ100％ハンバーグ（デミグラスソース）と人気のソーセージグリル2本とコンビ', price: 1780)
Menu.create(restaurant_id: restaurant_5.id, name: '真鯛のグリルレモンバターソース', image: 'westen6.png', description: '真鯛をステーキ風に仕上げました。バターソースにレモンを絞ってお召し上がりください。', price: 2180)
Menu.create(restaurant_id: restaurant_5.id, name: '黒毛和牛サーロインステーキ 150g', image: 'westen7.png', description: '和牛の中でも特に黒毛和牛は「霜降り」「色味」などが大変良い最高峰のステーキです。※画像はイメージです。ステーキはカットしてお持ちします。また付け合わせはフライドポテトとブロッコリーになります', price: 4980)
Menu.create(restaurant_id: restaurant_5.id, name: 'グリルセットA（ハンバーグ）', image: 'westen8.png', description: 'ハンバーグ×２、ソーセージ×２、ベーコン×２、オニオンリング、ライスコロッケ、フライドポテト（ケチャップ付き）※デミグラスソース付き（容器別添え）', price: 2680)

Menu.create(restaurant_id: restaurant_6.id, name: '【旨味熟成】溶岩焼ハラミビビンパ', image: 'korea1.png', description: '【卵付き】柔らかジューシーハラミ焼肉！当店自慢のカリカリッおこげ！溶岩プレートで焼き上げた美味しい “おこげ” をお召し上がりください。溶岩焼きの遠赤外線効果でワンランク上の味、カリカリッ “おこげ” がたまらない！ほどよい弾力が楽しめる、やわらかくてジューシーな熟成牛ハラミ！とキムチ＆こだわりのナムルを特製タレで味付け。卵黄を乗せてごはんと混ぜ合わせて絶品ビビンパをご堪能ください。溶岩焼きの遠赤外線効果でワンランク上の一味違う “おこげ” をお召し上がりください。', price: 1480)
Menu.create(restaurant_id: restaurant_6.id, name: '【人気NO1！】溶岩焼牛カルビビンパ', image: 'korea2.png', description: '【卵付き】特製旨たれ漬け込み牛カルビ！当店自慢のカリカリッおこげ！ 溶岩プレートで焼き上げた美味しい “おこげ” をお召し上がりください。溶岩焼きの遠赤外線効果でワンランク上の味、カリカリッ “おこげ” がたまらない！ うまみ溢れる漬け込み旨味牛カルビ！とキムチ＆こだわりのナムルを特製タレで味付け。卵黄を乗せてごはんと混ぜ合わせて絶品ビビンパをご堪能ください。 溶岩焼きの遠赤外線効果でワンランク上の一味違う “おこげ” をお召し上がりください。', price: 1180)
Menu.create(restaurant_id: restaurant_6.id, name: '【激辛注意！！】溶岩焼きプルダックビビンパ', image: 'korea3.png', description: '【卵付き】激辛 ‼ コクうまプルダック！当店自慢のカリカリッおこげ！ 溶岩プレートで焼き上げた美味しい “おこげ” をお召し上がりください。溶岩焼きの遠赤外線効果でワンランク上の味、カリカリッ “おこげ” がたまらない！辛い！けどうまいっ！ジューシーな鶏肉！とキムチ＆こだわりのナムルを特製タレで味付け。卵黄を乗せてごはんと混ぜ合わせて絶品ビビンパをご堪能ください。溶岩焼きの遠赤外線効果でワンランク上の一味違う “おこげ” をお召し上がりください。', price: 1180)
Menu.create(restaurant_id: restaurant_6.id, name: '【ボリューム抜群！】溶岩焼タッカルビビンパ', image: 'korea4.png', description: '【卵付き】甘辛コクうまタッカルビ！ 当店自慢のカリカリッおこげ！ 溶岩プレートで焼き上げた美味しい “おこげ” をお召し上がりください。溶岩焼きの遠赤外線効果でワンランク上の味、カリカリッ “おこげ” がたまらない！ 甘辛コクうまジューシーな鶏肉！とキムチ＆こだわりのナムルを特製タレで味付け。卵黄を乗せてごはんと混ぜ合わせて絶品ビビンパをご堪能ください。 溶岩焼きの遠赤外線効果でワンランク上の一味違う “おこげ” をお召し上がりください。', price: 1180)
Menu.create(restaurant_id: restaurant_6.id, name: '【ファルファサン特性】肉そぼろ丼', image: 'korea5.png', description: '甘辛うまっ♡ 自家製ビビンパミートの特製肉そぼろ丼です。美味しいナムルも添えました！『ファルファサン特製』甘辛の肉そぼろ丼！3種類のナムル(キムチ・もやし・小松菜)も一緒に！美味しいです。', price: 1240)
Menu.create(restaurant_id: restaurant_6.id, name: 'ナムル盛り合わせ', image: 'korea6.png', description: 'ナムル４種類の盛り合わせです。', price: 216)

Menu.create(restaurant_id: restaurant_7.id, name: '紫芋ミルクティー', image: 'beverage1.png', description: '(M)タピオカや他のトッピング最初入ってないので、トッピング一覧からお選びください。', price: 550)
Menu.create(restaurant_id: restaurant_7.id, name: 'BOBOマンゴーミルク', image: 'beverage2.png', description: '黒糖タピオカ30%増量付き、氷の量と甘さの量を選びません。 事故防止のため蓋からラップに変更させていただきます。今までのイメージとは少し変わってしまうので申し訳ございませんがご理解よろしくお願い申しあげます。', price: 690)
Menu.create(restaurant_id: restaurant_7.id, name: '抹茶きなこ', image: 'beverage3.png', description: '黒糖タピオカ付き、氷の量と甘さを選ぶことができません', price: 690)
Menu.create(restaurant_id: restaurant_7.id, name: '烏煎道きなこ', image: 'beverage4.png', description: 'タピオカや他トッピング入っておりません。トッピング一覧からお選びください。', price: 620)
Menu.create(restaurant_id: restaurant_7.id, name: 'Jasmine Peach Soda', image: 'beverage5.png', description: '(M)', price: 540)
Menu.create(restaurant_id: restaurant_7.id, name: 'BoBoドラベリー', image: 'beverage6.png', description: '黒糖タピオカ30%増量付き、氷の量と甘さの量を選びません。 事故防止のため蓋からラップに変更させていただきます。今までのイメージ', price: 690)

Menu.create(restaurant_id: restaurant_8.id, name: 'familyA', image: 'india1.png', description: '【セット内容】レギュラーカレー3種類（キーマ・バターチキン・ベジタブル）ナン×3ライス×1タンドリーチキン3Pサモサ3Pセット 内容変更、ライス大盛は行っておりません。', price: 3980)
Menu.create(restaurant_id: restaurant_8.id, name: 'familyB', image: 'india2.png', description: '【セット内容】レギュラーカレー3種類（キーマ・バターチキン・ベジタブル）ナン×1チーズナン×1ガーリックナン×1カブリナン×1タンドリーチキン4Pサモサ4Pセット内容変更は行っておりません。', price: 4980)
Menu.create(restaurant_id: restaurant_8.id, name: 'familyC', image: 'india3.png', description: '【セット内容】レギュラーカレー3種類（キーマ・バターチキン・ベジタブル）ナン×1チーズナン×1ガーリックナン×1カブリナン×1タンドリーチキン4Pサモサ4Pセット内容変更は行っておりません。', price: 5980)
Menu.create(restaurant_id: restaurant_8.id, name: 'T-MIX-3P', image: 'india4.png', description: 'ボリューム満点！タンドーリ焼き3種盛り！・ガーリックチキンティッカ（骨なしクリーミーチキン焼）・タンドーリチキン（骨付きスパイシーチキン焼）・シークカバブ（羊肉つくね風串焼き）', price: 990)
Menu.create(restaurant_id: restaurant_8.id, name: 'CHIKEN-P', image: 'india5.png', description: '豆の粉を衣にして揚げたスパイシーなインドの鶏のから揚げです。', price: 290)
Menu.create(restaurant_id: restaurant_8.id, name: 'C-BENTOU', image: 'india6.png', description: '【弁当の内容】■カレー1種類■目玉焼き■ナン＆ライス　　迷ったらこれ！', price: 990)

Menu.create(restaurant_id: restaurant_9.id, name: 'Thai Yakisoba', image: 'thai1.png', description: 'A non-spicy pad thai seasoned with tamarind sauce to bring out the flavors.', price: 1080)
Menu.create(restaurant_id: restaurant_9.id, name: 'Stir-Fried Gapao and Meat', image: 'thai2.png', description: 'The gapao is infused with flavor from the basil leaves, meat and vegetables.', price: 1080)
Menu.create(restaurant_id: restaurant_9.id, name: 'Tom Yum Kung Noodles', image: 'thai3.png', description: 'We have added noodles into the tom yum kung soup, one of the world best 3 soups. Enjoy this delicious flavor.', price: 1080)
Menu.create(restaurant_id: restaurant_9.id, name: 'Salad with Glass Noodles, Vegetables and Seafood', image: 'thai4.png', description: 'A spicy glass noodles salad with shrimp and squid.', price: 1080)
Menu.create(restaurant_id: restaurant_9.id, name: 'Freshly Boiled Squid Spicy Salad', image: 'thai5.png', description: 'A salad with freshly boiled squid, mint and lemongrass, as well has nam pla and chili.', price: 1080)
Menu.create(restaurant_id: restaurant_9.id, name: 'Thai-Style Grilled Chicken', image: 'thai6.png', description: 'The nam pla and garlic seasoned chicken is slowly grilled.', price: 1080)

Menu.create(restaurant_id: restaurant_10.id, name: 'シナモンアップル', image: 'cake1.png', description: 'ソフトな生地にシナモンフィリングとアップルプレザーブを巻き込んで焼き上げ、シナモンフォンダンで仕上げました。（アレルゲン28品目）小麦・卵・乳・大豆・りんご', price: 270)
Menu.create(restaurant_id: restaurant_10.id, name: '卵とミルクのクリームパン', image: 'cake2.png', description: '素材の味を生かした卵と牛乳のおいしさを感じられるクリームパンです。（アレルゲン28品目）小麦・卵・乳・アーモンド・大豆', price: 270)
Menu.create(restaurant_id: restaurant_10.id, name: 'ロイヤルミルク', image: 'cake3.png', description: 'ミルク風味のクリームを巻き込んだ菓子パンです。当店自慢の人気商品です。（アレルゲン28品目）小麦・卵・乳・大豆', price: 270)
Menu.create(restaurant_id: restaurant_10.id, name: 'パウンドケーキ フルーツ', image: 'cake4.png', description: '5種のフルーツ（オレンジピール、レーズン、チェリー、アップル、パイン）を練り込み、クルミをのせて焼き上げました。（アレルゲン28品目）小麦・卵・乳・オレンジ・くるみ・大豆・りんご', price: 640)
Menu.create(restaurant_id: restaurant_10.id, name: '北海道たっぷりコーン', image: 'cake5.png', description: 'ソフトなパン生地に、北海道産のスイートコーンをたっぷりのせました。（アレルゲン28品目）小麦・卵・乳・大豆・りんご', price: 290)
Menu.create(restaurant_id: restaurant_10.id, name: 'ミックスランチ', image: 'cake6.png', description: 'たまご、ロースハム、北海道産の野菜を使用したポテトサラダに、レタスをサンドした彩りの良い３種類のサンドイッチです。（アレルゲン28品目）小麦・卵・乳・さけ・ゼラチン・大豆・豚肉・りんご', price: 720)